// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOYVuFozQSdJao7DixIChpBkjac_zXqZg',
    appId: '1:1068561620607:web:328198c2e5e59bb24a294a',
    messagingSenderId: '1068561620607',
    projectId: 'feedikoi-project',
    authDomain: 'feedikoi-project.firebaseapp.com',
    storageBucket: 'feedikoi-project.firebasestorage.app',
    measurementId: 'G-02EP7QFBFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADYfL3whMiajdyzC9jhiAdcxgBS-qNyxU',
    appId: '1:1068561620607:android:eb4e39e8569f03284a294a',
    messagingSenderId: '1068561620607',
    projectId: 'feedikoi-project',
    storageBucket: 'feedikoi-project.firebasestorage.app',
  );
}
